name: Linting

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: npm install --legacy-peer-deps
      - name: eslint
        uses: icrawl/action-eslint@v1
